version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: farmlokal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: farmlokal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: farmlokal-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
